-- C2C Soporte - base local historial, cajeros y proyeccion folios
-- Ejecutar conectado a la base local soporte.
-- No ejecutar en produccion.
-- No apunta a public. Crea objetos locales en rr_gestion_soporte.

CREATE TABLE IF NOT EXISTS rr_gestion_soporte.documentos_historial_anual_resumen (
  resumen_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  anio integer NOT NULL,
  tenant_id uuid NOT NULL,
  rut integer,
  device_id varchar(255),
  tipodocumento integer,
  documentos_emitidos bigint NOT NULL DEFAULT 0,
  primer_folio_emitido integer,
  ultimo_folio_emitido integer,
  primera_emision date,
  ultima_emision date,
  valor_total_documentos bigint NOT NULL DEFAULT 0,
  origen text NOT NULL DEFAULT 'annual_readonly_summary',
  cargado_en timestamp without time zone NOT NULL DEFAULT now(),
  observacion text,
  CONSTRAINT documentos_historial_anual_resumen_unique
    UNIQUE NULLS NOT DISTINCT (anio, tenant_id, rut, device_id, tipodocumento)
);

COMMENT ON TABLE rr_gestion_soporte.documentos_historial_anual_resumen IS
  'Resumen anual historico agregado. No contiene documentos completos.';

CREATE TABLE IF NOT EXISTS rr_gestion_soporte.folios_alerta_config (
  config_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id uuid,
  rut integer,
  document_type integer,
  minimo_folios_warning integer NOT NULL DEFAULT 30000,
  minimo_folios_urgente integer NOT NULL DEFAULT 10000,
  dias_agotamiento_warning integer NOT NULL DEFAULT 30,
  dias_agotamiento_urgente integer NOT NULL DEFAULT 15,
  dias_sin_emision_warning integer NOT NULL DEFAULT 3,
  dias_sin_emision_urgente integer NOT NULL DEFAULT 7,
  activo boolean NOT NULL DEFAULT true,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  updated_at timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT folios_alerta_config_scope_unique
    UNIQUE (tenant_id, rut, document_type)
);

COMMENT ON TABLE rr_gestion_soporte.folios_alerta_config IS
  'Configuracion local de umbrales para alertas de folios y emision.';

INSERT INTO rr_gestion_soporte.folios_alerta_config (
  tenant_id,
  rut,
  document_type,
  minimo_folios_warning,
  minimo_folios_urgente,
  dias_agotamiento_warning,
  dias_agotamiento_urgente,
  dias_sin_emision_warning,
  dias_sin_emision_urgente
)
SELECT
  NULL,
  NULL,
  NULL,
  30000,
  10000,
  30,
  15,
  3,
  7
WHERE NOT EXISTS (
  SELECT 1
  FROM rr_gestion_soporte.folios_alerta_config
  WHERE tenant_id IS NULL
    AND rut IS NULL
    AND document_type IS NULL
);

CREATE TABLE IF NOT EXISTS rr_gestion_soporte.proceso_historial_anual_log (
  proceso_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  anio integer NOT NULL,
  estado text NOT NULL,
  iniciado_en timestamp without time zone NOT NULL DEFAULT now(),
  finalizado_en timestamp without time zone,
  filas_resumen bigint,
  mensaje text,
  ejecutado_por text
);

COMMENT ON TABLE rr_gestion_soporte.proceso_historial_anual_log IS
  'Auditoria local de ejecuciones manuales de resumen historico anual.';

CREATE OR REPLACE VIEW rr_gestion_soporte.cajero_emision_mensual AS
SELECT
  d.tenant_id,
  t.name AS tenant_name,
  d.rut,
  e.name AS empresa_name,
  d.device_id,
  dev.name AS device_name,
  dev.status AS device_status,
  d.tipodocumento AS document_type,
  d.periodo,
  d.documentos,
  d.primera_emision,
  d.ultima_emision,
  d.total_valor_documentos,
  dense_rank() OVER (
    PARTITION BY d.tenant_id, d.periodo
    ORDER BY d.documentos DESC
  ) AS ranking_mensual_tenant
FROM rr_gestion_soporte.documentos_2026_device_mensual d
LEFT JOIN staging_public.device dev
  ON dev.tenant_id = d.tenant_id
 AND dev.device_id = d.device_id
LEFT JOIN staging_public.tenant t
  ON t.tenant_id = d.tenant_id
LEFT JOIN staging_public.empresa e
  ON e.tenant_id = d.tenant_id
 AND e.rut = d.rut;

COMMENT ON VIEW rr_gestion_soporte.cajero_emision_mensual IS
  'Emision mensual 2026 por cajero/device con ranking por tenant.';

CREATE OR REPLACE VIEW rr_gestion_soporte.cajero_control_resumen AS
WITH actividad AS (
  SELECT
    tenant_id,
    rut,
    device_id,
    tipodocumento AS document_type,
    count(*)::bigint AS documentos_emitidos_2026,
    min(fecha_emision) AS primera_emision,
    max(fecha_emision) AS ultima_emision,
    min(folio) AS primer_folio_emitido,
    max(folio) AS ultimo_folio_emitido,
    count(*) FILTER (WHERE fecha_emision >= current_date - interval '30 days')::bigint AS documentos_30d,
    count(*) FILTER (WHERE fecha_emision >= current_date - interval '90 days')::bigint AS documentos_90d
  FROM rr_gestion_soporte.documentos_2026_normalizados
  GROUP BY tenant_id, rut, device_id, tipodocumento
),
historico AS (
  SELECT
    tenant_id,
    rut,
    device_id,
    tipodocumento AS document_type,
    sum(documentos_emitidos)::bigint AS documentos_historicos,
    min(primera_emision) AS primera_emision_historica,
    max(ultima_emision) AS ultima_emision_historica,
    min(primer_folio_emitido) AS primer_folio_historico,
    max(ultimo_folio_emitido) AS ultimo_folio_historico
  FROM rr_gestion_soporte.documentos_historial_anual_resumen
  GROUP BY tenant_id, rut, device_id, tipodocumento
)
SELECT
  dev.tenant_id,
  t.name AS tenant_name,
  coalesce(a.rut, h.rut) AS rut,
  e.name AS empresa_name,
  dev.device_id,
  dev.name AS device_name,
  dev.status AS device_status,
  coalesce(a.document_type, h.document_type) AS document_type,
  dev.created_at,
  CASE
    WHEN dev.created_at IS NULL THEN NULL
    ELSE current_date - dev.created_at::date
  END AS dias_desde_creacion,
  coalesce(h.documentos_historicos, 0) AS documentos_historicos,
  coalesce(a.documentos_emitidos_2026, 0) AS documentos_emitidos_2026,
  coalesce(a.documentos_30d, 0) AS documentos_30d,
  coalesce(a.documentos_90d, 0) AS documentos_90d,
  round(coalesce(a.documentos_30d, 0)::numeric / 30, 2) AS promedio_diario_30d,
  round(coalesce(a.documentos_90d, 0)::numeric / 90, 2) AS promedio_diario_90d,
  coalesce(h.primera_emision_historica, a.primera_emision) AS primera_emision,
  coalesce(a.ultima_emision, h.ultima_emision_historica) AS ultima_emision,
  coalesce(h.primer_folio_historico, a.primer_folio_emitido) AS primer_folio_emitido,
  coalesce(a.ultimo_folio_emitido, h.ultimo_folio_historico) AS ultimo_folio_emitido,
  CASE
    WHEN coalesce(a.ultima_emision, h.ultima_emision_historica) IS NULL THEN NULL
    ELSE current_date - coalesce(a.ultima_emision, h.ultima_emision_historica)
  END AS dias_sin_emision,
  CASE
    WHEN coalesce(a.ultima_emision, h.ultima_emision_historica) IS NULL THEN 'SIN_EMISION'
    WHEN current_date - coalesce(a.ultima_emision, h.ultima_emision_historica) >= 30 THEN 'PELIGRO'
    WHEN current_date - coalesce(a.ultima_emision, h.ultima_emision_historica) >= 15 THEN 'CRITICO'
    WHEN current_date - coalesce(a.ultima_emision, h.ultima_emision_historica) >= 7 THEN 'ALERTA'
    WHEN current_date - coalesce(a.ultima_emision, h.ultima_emision_historica) >= 3 THEN 'WARNING'
    WHEN current_date - coalesce(a.ultima_emision, h.ultima_emision_historica) >= 1 THEN 'OBSERVACION'
    ELSE 'NORMAL'
  END AS estado_operacional_cajero
FROM staging_public.device dev
LEFT JOIN actividad a
  ON a.tenant_id = dev.tenant_id
 AND a.device_id = dev.device_id
LEFT JOIN historico h
  ON h.tenant_id = dev.tenant_id
 AND h.device_id = dev.device_id
 AND (a.rut IS NULL OR h.rut = a.rut)
 AND (a.document_type IS NULL OR h.document_type = a.document_type)
LEFT JOIN staging_public.tenant t
  ON t.tenant_id = dev.tenant_id
LEFT JOIN staging_public.empresa e
  ON e.tenant_id = dev.tenant_id
 AND e.rut = coalesce(a.rut, h.rut);

COMMENT ON VIEW rr_gestion_soporte.cajero_control_resumen IS
  'Control de cajeros/devices con emision 2026, resumen historico anual opcional y primer/ultimo folio.';

CREATE OR REPLACE VIEW rr_gestion_soporte.folios_proyeccion_agotamiento AS
WITH config_resuelta AS (
  SELECT DISTINCT ON (f.tenant_id, f.rut, f.document_type)
    f.tenant_id,
    f.rut,
    f.document_type,
    c.minimo_folios_warning,
    c.minimo_folios_urgente,
    c.dias_agotamiento_warning,
    c.dias_agotamiento_urgente
  FROM rr_gestion_soporte.folios_control_resumen f
  JOIN rr_gestion_soporte.folios_alerta_config c
    ON c.activo
   AND (c.tenant_id IS NULL OR c.tenant_id = f.tenant_id)
   AND (c.rut IS NULL OR c.rut = f.rut)
   AND (c.document_type IS NULL OR c.document_type = f.document_type)
  ORDER BY
    f.tenant_id,
    f.rut,
    f.document_type,
    CASE WHEN c.tenant_id IS NULL THEN 1 ELSE 0 END,
    CASE WHEN c.rut IS NULL THEN 1 ELSE 0 END,
    CASE WHEN c.document_type IS NULL THEN 1 ELSE 0 END
),
consumo AS (
  SELECT
    tenant_id,
    rut,
    tipodocumento AS document_type,
    count(*) FILTER (WHERE fecha_emision >= current_date - interval '30 days')::bigint AS documentos_30d,
    count(*) FILTER (WHERE fecha_emision >= current_date - interval '90 days')::bigint AS documentos_90d
  FROM rr_gestion_soporte.documentos_2026_normalizados
  GROUP BY tenant_id, rut, tipodocumento
),
historico AS (
  SELECT
    tenant_id,
    rut,
    tipodocumento AS document_type,
    sum(documentos_emitidos)::bigint AS documentos_historicos,
    count(DISTINCT anio)::bigint AS anios_historicos
  FROM rr_gestion_soporte.documentos_historial_anual_resumen
  GROUP BY tenant_id, rut, tipodocumento
)
SELECT
  f.tenant_id,
  f.tenant_name,
  f.rut,
  f.empresa_name,
  f.document_type,
  f.folios_disponibles,
  f.nivel_alerta_folios,
  coalesce(con.documentos_30d, 0) AS documentos_30d,
  coalesce(con.documentos_90d, 0) AS documentos_90d,
  coalesce(h.documentos_historicos, 0) AS documentos_historicos,
  coalesce(h.anios_historicos, 0) AS anios_historicos,
  round(coalesce(con.documentos_30d, 0)::numeric / 30, 2) AS promedio_diario_30d,
  round(coalesce(con.documentos_90d, 0)::numeric / 90, 2) AS promedio_diario_90d,
  CASE
    WHEN coalesce(h.anios_historicos, 0) = 0 THEN NULL
    ELSE round((h.documentos_historicos::numeric / h.anios_historicos) / 365, 2)
  END AS promedio_diario_historico,
  CASE
    WHEN coalesce(con.documentos_30d, 0) = 0 THEN NULL
    ELSE round(f.folios_disponibles::numeric / (con.documentos_30d::numeric / 30), 2)
  END AS dias_hasta_agotar_30d,
  CASE
    WHEN coalesce(con.documentos_90d, 0) = 0 THEN NULL
    ELSE round(f.folios_disponibles::numeric / (con.documentos_90d::numeric / 90), 2)
  END AS dias_hasta_agotar_90d,
  cfg.minimo_folios_warning,
  cfg.minimo_folios_urgente,
  cfg.dias_agotamiento_warning,
  cfg.dias_agotamiento_urgente,
  CASE
    WHEN coalesce(con.documentos_30d, 0) = 0
     AND coalesce(con.documentos_90d, 0) = 0
     AND coalesce(h.documentos_historicos, 0) = 0 THEN 'SIN_BASE_ESTIMACION'
    WHEN f.folios_disponibles <= cfg.minimo_folios_urgente THEN 'URGENTE'
    WHEN coalesce(
      f.folios_disponibles::numeric / nullif(con.documentos_30d::numeric / 30, 0),
      f.folios_disponibles::numeric / nullif(con.documentos_90d::numeric / 90, 0)
    ) <= cfg.dias_agotamiento_urgente THEN 'URGENTE'
    WHEN f.folios_disponibles <= cfg.minimo_folios_warning THEN 'WARNING'
    WHEN coalesce(
      f.folios_disponibles::numeric / nullif(con.documentos_30d::numeric / 30, 0),
      f.folios_disponibles::numeric / nullif(con.documentos_90d::numeric / 90, 0)
    ) <= cfg.dias_agotamiento_warning THEN 'WARNING'
    ELSE 'OK'
  END AS nivel_alerta_agotamiento
FROM rr_gestion_soporte.folios_control_resumen f
LEFT JOIN consumo con
  ON con.tenant_id = f.tenant_id
 AND con.rut = f.rut
 AND con.document_type = f.document_type
LEFT JOIN historico h
  ON h.tenant_id = f.tenant_id
 AND h.rut = f.rut
 AND h.document_type = f.document_type
LEFT JOIN config_resuelta cfg
  ON cfg.tenant_id = f.tenant_id
 AND cfg.rut = f.rut
 AND cfg.document_type = f.document_type;

COMMENT ON VIEW rr_gestion_soporte.folios_proyeccion_agotamiento IS
  'Estimacion local de agotamiento de folios segun disponibles, consumo reciente e historico anual.';

CREATE OR REPLACE VIEW rr_gestion_soporte.folios_rangos_estado AS
WITH uso_rango AS (
  SELECT
    c.cafserial,
    count(d.*)::bigint AS documentos_rango_2026,
    min(d.folio) AS primer_folio_emitido_2026,
    max(d.folio) AS ultimo_folio_emitido_2026,
    max(d.fecha_emision) AS ultima_emision_rango_2026
  FROM staging_public.caf c
  LEFT JOIN rr_gestion_soporte.documentos_2026_normalizados d
    ON d.tenant_id = c.tenant_id
   AND d.rut = c.rut
   AND d.tipodocumento = c.document_type
   AND d.folio BETWEEN c.folio_ini AND c.folio_fin
  GROUP BY c.cafserial
)
SELECT
  c.tenant_id,
  t.name AS tenant_name,
  c.rut,
  e.name AS empresa_name,
  c.document_type,
  c.cafserial,
  c.folio_ini,
  c.folio_fin,
  (c.folio_fin - c.folio_ini + 1)::bigint AS folios_rango,
  c.created_at AS caf_created_at,
  u.documentos_rango_2026,
  u.primer_folio_emitido_2026,
  u.ultimo_folio_emitido_2026,
  u.ultima_emision_rango_2026,
  CASE
    WHEN u.documentos_rango_2026 = 0
     AND c.created_at::date <= current_date - interval '2 years' THEN 'CADUCADO_CANDIDATO'
    WHEN u.documentos_rango_2026 = 0 THEN 'POR_OCUPAR'
    WHEN u.ultimo_folio_emitido_2026 >= c.folio_fin THEN 'AGOTADO'
    WHEN u.ultimo_folio_emitido_2026 < c.folio_fin THEN 'EN_USO'
    ELSE 'REVISION_DATOS'
  END AS estado_rango
FROM staging_public.caf c
LEFT JOIN uso_rango u
  ON u.cafserial = c.cafserial
LEFT JOIN staging_public.tenant t
  ON t.tenant_id = c.tenant_id
LEFT JOIN staging_public.empresa e
  ON e.tenant_id = c.tenant_id
 AND e.rut = c.rut;

COMMENT ON VIEW rr_gestion_soporte.folios_rangos_estado IS
  'Estado candidato de rangos CAF para soporte. Caducidad final requiere validar xml_caf o regla SII.';
