BEGIN;

CREATE TABLE IF NOT EXISTS rr_gestion_soporte.helpdesk_catalog
(
    catalog_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    catalog_type varchar(60) NOT NULL,
    code varchar(80) NOT NULL,
    name varchar(160) NOT NULL,
    description text,
    color_hex varchar(7),
    sort_order integer NOT NULL DEFAULT 100,
    is_final_status boolean NOT NULL DEFAULT false,
    response_minutes integer,
    active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT helpdesk_catalog_type_code_key UNIQUE (catalog_type, code)
);

COMMENT ON TABLE rr_gestion_soporte.helpdesk_catalog
    IS 'Catalogos locales de Mesa de Ayuda: estados, prioridades, canales, tipos, ubicaciones, herramientas y categorias.';

CREATE TABLE IF NOT EXISTS rr_gestion_soporte.helpdesk_assignee
(
    assignee_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(80) NOT NULL,
    email varchar(255),
    display_name varchar(200) NOT NULL,
    role_name varchar(120),
    active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT helpdesk_assignee_username_key UNIQUE (username),
    CONSTRAINT helpdesk_assignee_email_key UNIQUE (email)
);

COMMENT ON TABLE rr_gestion_soporte.helpdesk_assignee
    IS 'Responsables internos que pueden tomar tickets de soporte.';

CREATE TABLE IF NOT EXISTS rr_gestion_soporte.helpdesk_contact
(
    contact_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    display_name varchar(200) NOT NULL,
    alias varchar(200),
    email varchar(255),
    phone_1 varchar(30),
    phone_2 varchar(30),
    position_name varchar(120),
    department_name varchar(120),
    contact_rut varchar(20),
    tenant_id uuid,
    rut varchar(20),
    company_name_snapshot varchar(220),
    status varchar(30) NOT NULL DEFAULT 'ACTIVO',
    notes text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE rr_gestion_soporte.helpdesk_contact
    IS 'Contactos operativos de soporte. Diferente a contactos administrativos formales de tenant.';

CREATE TABLE IF NOT EXISTS rr_gestion_soporte.helpdesk_ticket
(
    ticket_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_number bigint GENERATED BY DEFAULT AS IDENTITY,
    title text NOT NULL,
    description text,
    status_code varchar(80) NOT NULL DEFAULT 'OPEN',
    priority_code varchar(80) NOT NULL DEFAULT 'MEDIUM',
    category_code varchar(80),
    support_type_code varchar(80),
    incident_type_code varchar(80),
    communication_type_code varchar(80),
    channel_code varchar(80),
    support_mode_code varchar(80),
    location_code varchar(80),
    source varchar(40) NOT NULL DEFAULT 'MANUAL',
    tenant_id uuid,
    rut varchar(20),
    company_name_snapshot varchar(220),
    contact_id integer,
    device_id text,
    document_type integer,
    cafserial text,
    folio_ini bigint,
    folio_fin bigint,
    alert_source varchar(80),
    alert_severity varchar(40),
    alert_entity_id text,
    reference_date date,
    requested_at timestamptz,
    executed_at timestamptz,
    due_at timestamptz,
    assigned_to integer,
    opened_by integer,
    closed_by integer,
    opened_at timestamptz NOT NULL DEFAULT now(),
    closed_at timestamptz,
    is_after_hours boolean NOT NULL DEFAULT false,
    is_late_record boolean GENERATED ALWAYS AS ((requested_at IS NOT NULL) AND (requested_at < opened_at)) STORED,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT helpdesk_ticket_number_key UNIQUE (ticket_number)
);

COMMENT ON TABLE rr_gestion_soporte.helpdesk_ticket
    IS 'Ticket principal de Mesa de Ayuda. Puede nacer manualmente o desde alertas operativas.';

COMMENT ON COLUMN rr_gestion_soporte.helpdesk_ticket.source
    IS 'Origen del ticket: MANUAL, ALERT, COMPANY, DEVICE, CAF, FOLIO_RANGE, DOCUMENT.';

COMMENT ON COLUMN rr_gestion_soporte.helpdesk_ticket.company_name_snapshot
    IS 'Nombre de empresa congelado al momento de crear el ticket.';

CREATE TABLE IF NOT EXISTS rr_gestion_soporte.helpdesk_ticket_event
(
    event_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id bigint NOT NULL,
    event_type varchar(60) NOT NULL,
    from_status_code varchar(80),
    to_status_code varchar(80),
    comment text,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_by integer,
    created_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE rr_gestion_soporte.helpdesk_ticket_event
    IS 'Timeline auditable de acciones sobre tickets.';

CREATE TABLE IF NOT EXISTS rr_gestion_soporte.helpdesk_ticket_link
(
    link_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id bigint NOT NULL,
    link_type varchar(60) NOT NULL,
    tenant_id uuid,
    rut varchar(20),
    device_id text,
    document_type integer,
    cafserial text,
    folio_ini bigint,
    folio_fin bigint,
    entity_id text,
    source varchar(80),
    created_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE rr_gestion_soporte.helpdesk_ticket_link
    IS 'Vinculos flexibles entre tickets y entidades operativas: alertas, devices, CAF, rangos, documentos o empresas.';

CREATE TABLE IF NOT EXISTS rr_gestion_soporte.helpdesk_ticket_time_entry
(
    time_entry_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id bigint NOT NULL,
    work_date date NOT NULL,
    started_at time NOT NULL,
    finished_at time NOT NULL,
    is_after_hours boolean NOT NULL DEFAULT false,
    notes text,
    created_by integer,
    created_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE rr_gestion_soporte.helpdesk_ticket_time_entry
    IS 'Registro de tiempos de trabajo asociados a un ticket.';

CREATE TABLE IF NOT EXISTS rr_gestion_soporte.helpdesk_tool
(
    tool_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tool_type varchar(50) NOT NULL,
    name varchar(120) NOT NULL,
    description text,
    active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT helpdesk_tool_type_name_key UNIQUE (tool_type, name)
);

COMMENT ON TABLE rr_gestion_soporte.helpdesk_tool
    IS 'Herramientas usadas durante la atencion de tickets.';

CREATE TABLE IF NOT EXISTS rr_gestion_soporte.helpdesk_ticket_tool
(
    ticket_tool_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id bigint NOT NULL,
    tool_id integer NOT NULL,
    notes text,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT helpdesk_ticket_tool_ticket_tool_key UNIQUE (ticket_id, tool_id)
);

COMMENT ON TABLE rr_gestion_soporte.helpdesk_ticket_tool
    IS 'Relacion muchos-a-muchos entre tickets y herramientas.';

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'helpdesk_ticket_contact_id_fkey'
    ) THEN
        ALTER TABLE rr_gestion_soporte.helpdesk_ticket
            ADD CONSTRAINT helpdesk_ticket_contact_id_fkey
            FOREIGN KEY (contact_id)
            REFERENCES rr_gestion_soporte.helpdesk_contact(contact_id)
            ON DELETE SET NULL;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'helpdesk_ticket_assigned_to_fkey'
    ) THEN
        ALTER TABLE rr_gestion_soporte.helpdesk_ticket
            ADD CONSTRAINT helpdesk_ticket_assigned_to_fkey
            FOREIGN KEY (assigned_to)
            REFERENCES rr_gestion_soporte.helpdesk_assignee(assignee_id)
            ON DELETE SET NULL;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'helpdesk_ticket_opened_by_fkey'
    ) THEN
        ALTER TABLE rr_gestion_soporte.helpdesk_ticket
            ADD CONSTRAINT helpdesk_ticket_opened_by_fkey
            FOREIGN KEY (opened_by)
            REFERENCES rr_gestion_soporte.helpdesk_assignee(assignee_id)
            ON DELETE SET NULL;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'helpdesk_ticket_closed_by_fkey'
    ) THEN
        ALTER TABLE rr_gestion_soporte.helpdesk_ticket
            ADD CONSTRAINT helpdesk_ticket_closed_by_fkey
            FOREIGN KEY (closed_by)
            REFERENCES rr_gestion_soporte.helpdesk_assignee(assignee_id)
            ON DELETE SET NULL;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'helpdesk_ticket_event_ticket_id_fkey'
    ) THEN
        ALTER TABLE rr_gestion_soporte.helpdesk_ticket_event
            ADD CONSTRAINT helpdesk_ticket_event_ticket_id_fkey
            FOREIGN KEY (ticket_id)
            REFERENCES rr_gestion_soporte.helpdesk_ticket(ticket_id)
            ON DELETE CASCADE;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'helpdesk_ticket_event_created_by_fkey'
    ) THEN
        ALTER TABLE rr_gestion_soporte.helpdesk_ticket_event
            ADD CONSTRAINT helpdesk_ticket_event_created_by_fkey
            FOREIGN KEY (created_by)
            REFERENCES rr_gestion_soporte.helpdesk_assignee(assignee_id)
            ON DELETE SET NULL;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'helpdesk_ticket_link_ticket_id_fkey'
    ) THEN
        ALTER TABLE rr_gestion_soporte.helpdesk_ticket_link
            ADD CONSTRAINT helpdesk_ticket_link_ticket_id_fkey
            FOREIGN KEY (ticket_id)
            REFERENCES rr_gestion_soporte.helpdesk_ticket(ticket_id)
            ON DELETE CASCADE;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'helpdesk_ticket_time_entry_ticket_id_fkey'
    ) THEN
        ALTER TABLE rr_gestion_soporte.helpdesk_ticket_time_entry
            ADD CONSTRAINT helpdesk_ticket_time_entry_ticket_id_fkey
            FOREIGN KEY (ticket_id)
            REFERENCES rr_gestion_soporte.helpdesk_ticket(ticket_id)
            ON DELETE CASCADE;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'helpdesk_ticket_time_entry_created_by_fkey'
    ) THEN
        ALTER TABLE rr_gestion_soporte.helpdesk_ticket_time_entry
            ADD CONSTRAINT helpdesk_ticket_time_entry_created_by_fkey
            FOREIGN KEY (created_by)
            REFERENCES rr_gestion_soporte.helpdesk_assignee(assignee_id)
            ON DELETE SET NULL;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'helpdesk_ticket_tool_ticket_id_fkey'
    ) THEN
        ALTER TABLE rr_gestion_soporte.helpdesk_ticket_tool
            ADD CONSTRAINT helpdesk_ticket_tool_ticket_id_fkey
            FOREIGN KEY (ticket_id)
            REFERENCES rr_gestion_soporte.helpdesk_ticket(ticket_id)
            ON DELETE CASCADE;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'helpdesk_ticket_tool_tool_id_fkey'
    ) THEN
        ALTER TABLE rr_gestion_soporte.helpdesk_ticket_tool
            ADD CONSTRAINT helpdesk_ticket_tool_tool_id_fkey
            FOREIGN KEY (tool_id)
            REFERENCES rr_gestion_soporte.helpdesk_tool(tool_id)
            ON DELETE RESTRICT;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_helpdesk_ticket_status
    ON rr_gestion_soporte.helpdesk_ticket(status_code);

CREATE INDEX IF NOT EXISTS idx_helpdesk_ticket_priority
    ON rr_gestion_soporte.helpdesk_ticket(priority_code);

CREATE INDEX IF NOT EXISTS idx_helpdesk_ticket_tenant
    ON rr_gestion_soporte.helpdesk_ticket(tenant_id);

CREATE INDEX IF NOT EXISTS idx_helpdesk_ticket_rut
    ON rr_gestion_soporte.helpdesk_ticket(rut);

CREATE INDEX IF NOT EXISTS idx_helpdesk_ticket_device
    ON rr_gestion_soporte.helpdesk_ticket(device_id);

CREATE INDEX IF NOT EXISTS idx_helpdesk_ticket_opened_at
    ON rr_gestion_soporte.helpdesk_ticket(opened_at DESC);

CREATE INDEX IF NOT EXISTS idx_helpdesk_ticket_event_ticket
    ON rr_gestion_soporte.helpdesk_ticket_event(ticket_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_helpdesk_ticket_link_ticket
    ON rr_gestion_soporte.helpdesk_ticket_link(ticket_id);

CREATE INDEX IF NOT EXISTS idx_helpdesk_ticket_link_entity
    ON rr_gestion_soporte.helpdesk_ticket_link(link_type, entity_id);

CREATE INDEX IF NOT EXISTS idx_helpdesk_contact_tenant
    ON rr_gestion_soporte.helpdesk_contact(tenant_id);

CREATE INDEX IF NOT EXISTS idx_helpdesk_contact_rut
    ON rr_gestion_soporte.helpdesk_contact(rut);

COMMIT;
