BEGIN;

CREATE TABLE IF NOT EXISTS rr_gestion_soporte.helpdesk_email_message
(
    email_message_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id bigint,
    provider varchar(40) NOT NULL DEFAULT 'SIMULATED',
    mailbox varchar(255),
    message_id varchar(512) NOT NULL,
    conversation_id varchar(512),
    from_email varchar(255) NOT NULL,
    from_name varchar(255),
    reply_to varchar(255),
    subject text NOT NULL,
    body_text text,
    body_preview text,
    received_at timestamptz NOT NULL,
    processed_at timestamptz,
    status varchar(40) NOT NULL DEFAULT 'RECEIVED',
    error_message text,
    tenant_id uuid,
    rut varchar(20),
    company_name_snapshot varchar(220),
    contact_id integer,
    hash_dedup varchar(128),
    raw_headers jsonb NOT NULL DEFAULT '{}'::jsonb,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT helpdesk_email_message_message_id_key UNIQUE (message_id),
    CONSTRAINT helpdesk_email_message_hash_dedup_key UNIQUE (hash_dedup)
);

COMMENT ON TABLE rr_gestion_soporte.helpdesk_email_message
    IS 'Trazabilidad local de mensajes de correo que originan o pueden originar tickets Helpdesk.';

COMMENT ON COLUMN rr_gestion_soporte.helpdesk_email_message.provider
    IS 'Proveedor de origen: SIMULATED, IMAP, MICROSOFT_GRAPH, GMAIL_API o WEBHOOK.';

COMMENT ON COLUMN rr_gestion_soporte.helpdesk_email_message.message_id
    IS 'Identificador unico del correo usado para evitar tickets duplicados.';

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'helpdesk_email_message_ticket_id_fkey'
    ) THEN
        ALTER TABLE rr_gestion_soporte.helpdesk_email_message
            ADD CONSTRAINT helpdesk_email_message_ticket_id_fkey
            FOREIGN KEY (ticket_id)
            REFERENCES rr_gestion_soporte.helpdesk_ticket(ticket_id)
            ON DELETE SET NULL;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'helpdesk_email_message_contact_id_fkey'
    ) THEN
        ALTER TABLE rr_gestion_soporte.helpdesk_email_message
            ADD CONSTRAINT helpdesk_email_message_contact_id_fkey
            FOREIGN KEY (contact_id)
            REFERENCES rr_gestion_soporte.helpdesk_contact(contact_id)
            ON DELETE SET NULL;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_helpdesk_email_message_ticket
    ON rr_gestion_soporte.helpdesk_email_message(ticket_id);

CREATE INDEX IF NOT EXISTS idx_helpdesk_email_message_status_received
    ON rr_gestion_soporte.helpdesk_email_message(status, received_at DESC);

CREATE INDEX IF NOT EXISTS idx_helpdesk_email_message_from_email
    ON rr_gestion_soporte.helpdesk_email_message(from_email);

COMMIT;
