-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS rr_gestion_soporte.tickets
(
    id integer NOT NULL DEFAULT nextval('rr_gestion_soporte.tickets_id_seq'::regclass),
    numero_item integer,
    rut_cliente character varying(20) COLLATE pg_catalog."default" NOT NULL,
    nombre_cliente character varying(200) COLLATE pg_catalog."default" NOT NULL,
    contacto_id integer,
    rut_cliente_preventivo character varying(20) COLLATE pg_catalog."default",
    nombre_cliente_preventivo character varying(200) COLLATE pg_catalog."default",
    fecha_creacion date NOT NULL DEFAULT CURRENT_DATE,
    hora_creacion time without time zone,
    fecha_solicitud date,
    hora_solicitud time without time zone,
    fecha_ejecucion date,
    hora_inicio time without time zone,
    hora_termino time without time zone,
    asunto text COLLATE pg_catalog."default" NOT NULL,
    detalle text COLLATE pg_catalog."default",
    tipo_soporte_id integer,
    tipo_incidente_id integer,
    modo_soporte_id integer,
    canal_id integer,
    tipo_comunicacion_id integer,
    ubicacion_id integer,
    prioridad_id integer DEFAULT 2,
    estado_id integer NOT NULL DEFAULT 1,
    responsable character varying(200) COLLATE pg_catalog."default" NOT NULL,
    es_fuera_horario boolean NOT NULL DEFAULT false,
    registrado_tarde boolean GENERATED ALWAYS AS (((fecha_solicitud IS NOT NULL) AND (fecha_solicitud < fecha_creacion))) STORED,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    id2 integer,
    registrado_por_id integer,
    CONSTRAINT tickets_pkey PRIMARY KEY (id),
    CONSTRAINT pkeyid_tickets UNIQUE (id),
    CONSTRAINT tickets_numero_item_key UNIQUE (numero_item)
);

COMMENT ON TABLE rr_gestion_soporte.tickets
    IS 'Tabla principal de tickets de soporte. Un registro por ticket.';

COMMENT ON COLUMN rr_gestion_soporte.tickets.numero_item
    IS 'N° correlativo visible para el usuario. Proviene del formulario original de Google Sheets.';

COMMENT ON COLUMN rr_gestion_soporte.tickets.detalle
    IS 'Descripción extendida del problema. El asunto es el resumen corto.';

COMMENT ON COLUMN rr_gestion_soporte.tickets.es_fuera_horario
    IS 'TRUE si el soporte fue entregado fuera del horario laboral habitual.';

COMMENT ON COLUMN rr_gestion_soporte.tickets.registrado_tarde
    IS 'TRUE si fecha_solicitud < fecha_creacion (el ticket fue registrado después de ejecutarse).';

CREATE TABLE IF NOT EXISTS rr_gestion_soporte.cat_canal
(
    id integer NOT NULL DEFAULT nextval('rr_gestion_soporte.cat_canal_id_seq'::regclass),
    nombre character varying(50) COLLATE pg_catalog."default" NOT NULL,
    observacion text COLLATE pg_catalog."default",
    activo boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT cat_canal_pkey PRIMARY KEY (id),
    CONSTRAINT cat_canal_nombre_key UNIQUE (nombre)
);

COMMENT ON TABLE rr_gestion_soporte.cat_canal
    IS 'Canal por el cual el cliente solicitó el soporte.';

CREATE TABLE IF NOT EXISTS rr_gestion_soporte.contactos_soporte
(
    id integer NOT NULL DEFAULT nextval('rr_gestion_soporte.contactos_soporte_id_seq'::regclass),
    nombre character varying(200) COLLATE pg_catalog."default" NOT NULL,
    alias character varying(200) COLLATE pg_catalog."default",
    email character varying(255) COLLATE pg_catalog."default",
    fono1 character varying(30) COLLATE pg_catalog."default",
    fono2 character varying(30) COLLATE pg_catalog."default",
    cargo character varying(120) COLLATE pg_catalog."default",
    depto character varying(120) COLLATE pg_catalog."default",
    rut character varying(20) COLLATE pg_catalog."default",
    rut_empresa character varying(20) COLLATE pg_catalog."default",
    nombre_empresa character varying(200) COLLATE pg_catalog."default",
    estado character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'ACTIVO'::character varying,
    observaciones text COLLATE pg_catalog."default",
    fecha_creacion date NOT NULL DEFAULT CURRENT_DATE,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT contactos_soporte_pkey PRIMARY KEY (id)
);

COMMENT ON TABLE rr_gestion_soporte.contactos_soporte
    IS 'Agenda de contactos de soporte diario. Diferente a contactos_administrativos que son formales por tenant.';

COMMENT ON COLUMN rr_gestion_soporte.contactos_soporte.alias
    IS 'Nombre informal, apodo, usuario del sistema o contexto (ej: "Fabián Net Parking Isabel La Católica").';

COMMENT ON COLUMN rr_gestion_soporte.contactos_soporte.estado
    IS 'ACTIVO: contacto verificado. REVISAR: importado, pendiente de limpieza. INACTIVO: ya no vigente.';

CREATE TABLE IF NOT EXISTS rr_gestion_soporte.cat_estado_ticket
(
    id integer NOT NULL DEFAULT nextval('rr_gestion_soporte.cat_estado_ticket_id_seq'::regclass),
    nombre character varying(50) COLLATE pg_catalog."default" NOT NULL,
    observacion text COLLATE pg_catalog."default",
    es_estado_final boolean NOT NULL DEFAULT false,
    color_hex character varying(7) COLLATE pg_catalog."default",
    activo boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT cat_estado_ticket_pkey PRIMARY KEY (id),
    CONSTRAINT cat_estado_ticket_nombre_key UNIQUE (nombre)
);

COMMENT ON TABLE rr_gestion_soporte.cat_estado_ticket
    IS 'Ciclo de vida de un ticket. es_estado_final=TRUE indica que el ticket no requiere más acción.';

COMMENT ON COLUMN rr_gestion_soporte.cat_estado_ticket.es_estado_final
    IS 'TRUE para estados Cerrado y Escalado (cuando es la resolución final).';

CREATE TABLE IF NOT EXISTS rr_gestion_soporte.ticket_acciones
(
    id integer NOT NULL DEFAULT nextval('rr_gestion_soporte.ticket_acciones_id_seq'::regclass),
    ticket_id integer NOT NULL,
    tipo_accion character varying(30) COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default" NOT NULL,
    estado_anterior_id integer,
    estado_nuevo_id integer,
    responsable character varying(200) COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT ticket_acciones_pkey PRIMARY KEY (id)
);

COMMENT ON TABLE rr_gestion_soporte.ticket_acciones
    IS 'Historial de todas las acciones realizadas sobre un ticket (cambios de estado, notas, trabajo).';

COMMENT ON COLUMN rr_gestion_soporte.ticket_acciones.tipo_accion
    IS 'CREACION | CAMBIO_ESTADO | NOTA | TRABAJO | ESCALADO';

CREATE TABLE IF NOT EXISTS rr_gestion_soporte.cat_modo_soporte
(
    id integer NOT NULL DEFAULT nextval('rr_gestion_soporte.cat_modo_soporte_id_seq'::regclass),
    nombre character varying(50) COLLATE pg_catalog."default" NOT NULL,
    observacion text COLLATE pg_catalog."default",
    activo boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT cat_modo_soporte_pkey PRIMARY KEY (id),
    CONSTRAINT cat_modo_soporte_nombre_key UNIQUE (nombre)
);

COMMENT ON TABLE rr_gestion_soporte.cat_modo_soporte
    IS 'Modalidad en que se entregó el soporte: Remoto, InSitu, Híbrido, Otros.';

CREATE TABLE IF NOT EXISTS rr_gestion_soporte.cat_prioridad
(
    id integer NOT NULL DEFAULT nextval('rr_gestion_soporte.cat_prioridad_id_seq'::regclass),
    nombre character varying(30) COLLATE pg_catalog."default" NOT NULL,
    color_hex character varying(7) COLLATE pg_catalog."default",
    tiempo_respuesta_minutos integer,
    activo boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT cat_prioridad_pkey PRIMARY KEY (id),
    CONSTRAINT cat_prioridad_nombre_key UNIQUE (nombre)
);

COMMENT ON TABLE rr_gestion_soporte.cat_prioridad
    IS 'Nivel de prioridad/urgencia del ticket con tiempo de respuesta esperado en minutos.';

CREATE TABLE IF NOT EXISTS rr_gestion_soporte.encargados_soporte
(
    id integer NOT NULL DEFAULT nextval('rr_gestion_soporte.encargados_soporte_id_seq'::regclass),
    usuario character varying(80) COLLATE pg_catalog."default" NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    nombre character varying(200) COLLATE pg_catalog."default",
    cargo character varying(120) COLLATE pg_catalog."default",
    activo boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT encargados_soporte_pkey PRIMARY KEY (id),
    CONSTRAINT encargados_soporte_email_key UNIQUE (email),
    CONSTRAINT encargados_soporte_usuario_key UNIQUE (usuario)
);

CREATE TABLE IF NOT EXISTS rr_gestion_soporte.cat_tipo_comunicacion
(
    id integer NOT NULL DEFAULT nextval('rr_gestion_soporte.cat_tipo_comunicacion_id_seq'::regclass),
    nombre character varying(50) COLLATE pg_catalog."default" NOT NULL,
    detalle text COLLATE pg_catalog."default",
    activo boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT cat_tipo_comunicacion_pkey PRIMARY KEY (id),
    CONSTRAINT cat_tipo_comunicacion_nombre_key UNIQUE (nombre)
);

COMMENT ON TABLE rr_gestion_soporte.cat_tipo_comunicacion
    IS 'Naturaleza y urgencia del contacto que originó el ticket.';

CREATE TABLE IF NOT EXISTS rr_gestion_soporte.cat_tipo_incidente
(
    id integer NOT NULL DEFAULT nextval('rr_gestion_soporte.cat_tipo_incidente_id_seq'::regclass),
    nombre character varying(50) COLLATE pg_catalog."default" NOT NULL,
    responsable character varying(50) COLLATE pg_catalog."default",
    descripcion text COLLATE pg_catalog."default",
    activo boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT cat_tipo_incidente_pkey PRIMARY KEY (id),
    CONSTRAINT cat_tipo_incidente_nombre_key UNIQUE (nombre)
);

COMMENT ON TABLE rr_gestion_soporte.cat_tipo_incidente
    IS 'Origen o causa del incidente. El campo responsable indica quién es el responsable del incidente.';

CREATE TABLE IF NOT EXISTS rr_gestion_soporte.cat_tipo_soporte
(
    id integer NOT NULL DEFAULT nextval('rr_gestion_soporte.cat_tipo_soporte_id_seq'::regclass),
    nombre character varying(50) COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default",
    activo boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT cat_tipo_soporte_pkey PRIMARY KEY (id),
    CONSTRAINT cat_tipo_soporte_nombre_key UNIQUE (nombre)
);

COMMENT ON TABLE rr_gestion_soporte.cat_tipo_soporte
    IS 'Tipo de soporte entregado: Correctivo, Preventivo, Informativo, Solicitud, Otros.';

CREATE TABLE IF NOT EXISTS rr_gestion_soporte.cat_ubicacion
(
    id integer NOT NULL DEFAULT nextval('rr_gestion_soporte.cat_ubicacion_id_seq'::regclass),
    nombre character varying(50) COLLATE pg_catalog."default" NOT NULL,
    observacion text COLLATE pg_catalog."default",
    activo boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT cat_ubicacion_pkey PRIMARY KEY (id),
    CONSTRAINT cat_ubicacion_nombre_key UNIQUE (nombre)
);

COMMENT ON TABLE rr_gestion_soporte.cat_ubicacion
    IS 'Ubicación física del técnico al momento de atender el ticket.';

CREATE TABLE IF NOT EXISTS rr_gestion_soporte.ticket_herramientas
(
    id integer NOT NULL DEFAULT nextval('rr_gestion_soporte.ticket_herramientas_id_seq'::regclass),
    ticket_id integer NOT NULL,
    herramienta_id integer NOT NULL,
    observacion text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT ticket_herramientas_pkey PRIMARY KEY (id),
    CONSTRAINT ticket_herramientas_ticket_id_herramienta_id_key UNIQUE (ticket_id, herramienta_id)
);

COMMENT ON TABLE rr_gestion_soporte.ticket_herramientas
    IS 'Herramientas usadas en cada ticket (relación muchos-a-muchos).';

CREATE TABLE IF NOT EXISTS rr_gestion_soporte.cat_herramientas
(
    id integer NOT NULL DEFAULT nextval('rr_gestion_soporte.cat_herramientas_id_seq'::regclass),
    tipo character varying(50) COLLATE pg_catalog."default" NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    observacion text COLLATE pg_catalog."default",
    activo boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT cat_herramientas_pkey PRIMARY KEY (id),
    CONSTRAINT cat_herramientas_tipo_nombre_key UNIQUE (tipo, nombre)
);

COMMENT ON TABLE rr_gestion_soporte.cat_herramientas
    IS 'Herramientas usadas durante la atención del ticket (SOFTWARE, DISPOSITIVO, OTROS).';

CREATE TABLE IF NOT EXISTS rr_gestion_soporte.ticket_tiempos
(
    id integer NOT NULL DEFAULT nextval('rr_gestion_soporte.ticket_tiempos_id_seq'::regclass),
    ticket_id integer NOT NULL,
    fecha date NOT NULL,
    hora_inicio time without time zone NOT NULL,
    hora_termino time without time zone NOT NULL,
    es_fuera_horario boolean NOT NULL DEFAULT false,
    observacion text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT ticket_tiempos_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS rr_gestion_soporte.tickets
    ADD CONSTRAINT tickets_canal_id_fkey FOREIGN KEY (canal_id)
    REFERENCES rr_gestion_soporte.cat_canal (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS rr_gestion_soporte.tickets
    ADD CONSTRAINT tickets_contacto_id_fkey FOREIGN KEY (contacto_id)
    REFERENCES rr_gestion_soporte.contactos_soporte (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_tickets_contacto
    ON rr_gestion_soporte.tickets(contacto_id);


ALTER TABLE IF EXISTS rr_gestion_soporte.tickets
    ADD CONSTRAINT tickets_estado_id_fkey FOREIGN KEY (estado_id)
    REFERENCES rr_gestion_soporte.cat_estado_ticket (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_tickets_estado
    ON rr_gestion_soporte.tickets(estado_id);


ALTER TABLE IF EXISTS rr_gestion_soporte.tickets
    ADD CONSTRAINT tickets_modo_soporte_id_fkey FOREIGN KEY (modo_soporte_id)
    REFERENCES rr_gestion_soporte.cat_modo_soporte (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS rr_gestion_soporte.tickets
    ADD CONSTRAINT tickets_prioridad_id_fkey FOREIGN KEY (prioridad_id)
    REFERENCES rr_gestion_soporte.cat_prioridad (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS rr_gestion_soporte.tickets
    ADD CONSTRAINT tickets_registrado_por_id_fkey FOREIGN KEY (registrado_por_id)
    REFERENCES rr_gestion_soporte.encargados_soporte (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_tickets_registrado_por
    ON rr_gestion_soporte.tickets(registrado_por_id);


ALTER TABLE IF EXISTS rr_gestion_soporte.tickets
    ADD CONSTRAINT tickets_tipo_comunicacion_id_fkey FOREIGN KEY (tipo_comunicacion_id)
    REFERENCES rr_gestion_soporte.cat_tipo_comunicacion (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS rr_gestion_soporte.tickets
    ADD CONSTRAINT tickets_tipo_incidente_id_fkey FOREIGN KEY (tipo_incidente_id)
    REFERENCES rr_gestion_soporte.cat_tipo_incidente (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS rr_gestion_soporte.tickets
    ADD CONSTRAINT tickets_tipo_soporte_id_fkey FOREIGN KEY (tipo_soporte_id)
    REFERENCES rr_gestion_soporte.cat_tipo_soporte (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_tickets_tipo_soporte
    ON rr_gestion_soporte.tickets(tipo_soporte_id);


ALTER TABLE IF EXISTS rr_gestion_soporte.tickets
    ADD CONSTRAINT tickets_ubicacion_id_fkey FOREIGN KEY (ubicacion_id)
    REFERENCES rr_gestion_soporte.cat_ubicacion (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS rr_gestion_soporte.ticket_acciones
    ADD CONSTRAINT ticket_acciones_estado_anterior_id_fkey FOREIGN KEY (estado_anterior_id)
    REFERENCES rr_gestion_soporte.cat_estado_ticket (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS rr_gestion_soporte.ticket_acciones
    ADD CONSTRAINT ticket_acciones_estado_nuevo_id_fkey FOREIGN KEY (estado_nuevo_id)
    REFERENCES rr_gestion_soporte.cat_estado_ticket (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS rr_gestion_soporte.ticket_acciones
    ADD CONSTRAINT ticket_acciones_ticket_id_fkey FOREIGN KEY (ticket_id)
    REFERENCES rr_gestion_soporte.tickets (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS rr_gestion_soporte.ticket_herramientas
    ADD CONSTRAINT ticket_herramientas_herramienta_id_fkey FOREIGN KEY (herramienta_id)
    REFERENCES rr_gestion_soporte.cat_herramientas (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS rr_gestion_soporte.ticket_herramientas
    ADD CONSTRAINT ticket_herramientas_ticket_id_fkey FOREIGN KEY (ticket_id)
    REFERENCES rr_gestion_soporte.tickets (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_ticket_herramientas_ticket
    ON rr_gestion_soporte.ticket_herramientas(ticket_id);


ALTER TABLE IF EXISTS rr_gestion_soporte.ticket_tiempos
    ADD CONSTRAINT ticket_tiempos_ticket_id_fkey FOREIGN KEY (ticket_id)
    REFERENCES rr_gestion_soporte.tickets (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

END;