-- C2C Soporte - control local de refresco de caches
-- Ejecutar conectado a la base local soporte.
-- No ejecutar en origen productivo.
-- No toca public. Crea auditoria local en rr_gestion_soporte.

CREATE TABLE IF NOT EXISTS rr_gestion_soporte.cache_refresh_log (
  refresh_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  status text NOT NULL,
  started_at timestamp without time zone NOT NULL DEFAULT now(),
  finished_at timestamp without time zone,
  duration_ms bigint,
  requested_by text,
  message text,
  cache_counts jsonb
);

COMMENT ON TABLE rr_gestion_soporte.cache_refresh_log IS
  'Auditoria local de refresco manual de caches del aplicativo C2C Helpdesk.';

CREATE INDEX IF NOT EXISTS idx_cache_refresh_log_started
  ON rr_gestion_soporte.cache_refresh_log (started_at DESC);

CREATE INDEX IF NOT EXISTS idx_cache_refresh_log_status
  ON rr_gestion_soporte.cache_refresh_log (status, started_at DESC);
