-- C2C Soporte - control local de vencimiento CAF facturas 33
-- Ejecutar conectado a la base local soporte.
-- No ejecutar en origen productivo.
-- No toca public. Extrae solo fecha FA desde xml_caf local.

CREATE TABLE IF NOT EXISTS rr_gestion_soporte.caf_vencimiento_config (
  config_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_type integer NOT NULL UNIQUE,
  document_label text NOT NULL,
  vigencia_meses integer,
  warning_dias integer NOT NULL DEFAULT 30,
  aplica_vencimiento boolean NOT NULL DEFAULT false,
  activo boolean NOT NULL DEFAULT true,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  updated_at timestamp without time zone NOT NULL DEFAULT now()
);

COMMENT ON TABLE rr_gestion_soporte.caf_vencimiento_config IS
  'Configuracion local de vigencia y umbrales de aviso CAF por tipo DTE.';

INSERT INTO rr_gestion_soporte.caf_vencimiento_config (
  document_type,
  document_label,
  vigencia_meses,
  warning_dias,
  aplica_vencimiento
)
VALUES
  (33, 'Factura electronica', 6, 30, true),
  (39, 'Boleta electronica', NULL, 30, false),
  (41, 'Boleta exenta electronica', NULL, 30, false)
ON CONFLICT (document_type) DO UPDATE
SET
  document_label = EXCLUDED.document_label,
  vigencia_meses = EXCLUDED.vigencia_meses,
  warning_dias = EXCLUDED.warning_dias,
  aplica_vencimiento = EXCLUDED.aplica_vencimiento,
  updated_at = now();

CREATE OR REPLACE VIEW rr_gestion_soporte.caf_vencimiento_resumen AS
WITH base AS (
  SELECT
    c.tenant_id,
    t.name AS tenant_name,
    c.rut,
    e.name AS empresa_name,
    c.document_type,
    cfg.document_label,
    cfg.vigencia_meses,
    cfg.warning_dias,
    coalesce(cfg.aplica_vencimiento, false) AS aplica_vencimiento,
    c.cafserial,
    c.folio_ini,
    c.folio_fin,
    c.created_at AS caf_created_at,
    substring(c.xml_caf FROM '<FA>([0-9]{4}-[0-9]{2}-[0-9]{2})</FA>') AS fa_text
  FROM staging_public.caf c
  LEFT JOIN staging_public.tenant t
    ON t.tenant_id = c.tenant_id
  LEFT JOIN staging_public.empresa e
    ON e.tenant_id = c.tenant_id
   AND e.rut = c.rut
  LEFT JOIN rr_gestion_soporte.caf_vencimiento_config cfg
    ON cfg.document_type = c.document_type
   AND cfg.activo
),
fechas AS (
  SELECT
    *,
    CASE
      WHEN fa_text IS NULL THEN NULL
      ELSE fa_text::date
    END AS caf_fecha_autorizacion
  FROM base
)
SELECT
  tenant_id,
  tenant_name,
  rut,
  empresa_name,
  document_type,
  cafserial,
  folio_ini,
  folio_fin,
  caf_created_at,
  caf_fecha_autorizacion,
  CASE
    WHEN aplica_vencimiento AND vigencia_meses IS NOT NULL AND caf_fecha_autorizacion IS NOT NULL
      THEN (caf_fecha_autorizacion + make_interval(months => vigencia_meses))::date
    ELSE NULL
  END AS caf_fecha_vencimiento,
  CASE
    WHEN aplica_vencimiento AND vigencia_meses IS NOT NULL AND caf_fecha_autorizacion IS NOT NULL
      THEN ((caf_fecha_autorizacion + make_interval(months => vigencia_meses))::date - current_date)
    ELSE NULL
  END AS caf_dias_para_vencer,
  CASE
    WHEN NOT aplica_vencimiento THEN 'NO_APLICA'
    WHEN caf_fecha_autorizacion IS NULL THEN 'SIN_FECHA_CAF'
    WHEN (caf_fecha_autorizacion + make_interval(months => vigencia_meses))::date <= current_date THEN 'URGENTE'
    WHEN (caf_fecha_autorizacion + make_interval(months => vigencia_meses))::date <= current_date + make_interval(days => warning_dias) THEN 'WARNING'
    ELSE 'OK'
  END AS nivel_alerta_caf_vencimiento,
  document_label,
  vigencia_meses,
  warning_dias,
  aplica_vencimiento
FROM fechas;

COMMENT ON VIEW rr_gestion_soporte.caf_vencimiento_resumen IS
  'Extraccion local de FA desde xml_caf y vencimiento operacional para CAF tipo 33.';

CREATE TABLE IF NOT EXISTS rr_gestion_soporte.caf_vencimiento_cache AS
SELECT *
FROM rr_gestion_soporte.caf_vencimiento_resumen;

ALTER TABLE rr_gestion_soporte.caf_vencimiento_cache
  ADD COLUMN IF NOT EXISTS document_label text,
  ADD COLUMN IF NOT EXISTS vigencia_meses integer,
  ADD COLUMN IF NOT EXISTS warning_dias integer,
  ADD COLUMN IF NOT EXISTS aplica_vencimiento boolean;

ALTER TABLE rr_gestion_soporte.folios_rangos_clasificados_cache
  ADD COLUMN IF NOT EXISTS caf_fecha_autorizacion date,
  ADD COLUMN IF NOT EXISTS caf_fecha_vencimiento date,
  ADD COLUMN IF NOT EXISTS caf_dias_para_vencer integer,
  ADD COLUMN IF NOT EXISTS nivel_alerta_caf_vencimiento text,
  ADD COLUMN IF NOT EXISTS document_label text,
  ADD COLUMN IF NOT EXISTS vigencia_meses integer,
  ADD COLUMN IF NOT EXISTS warning_dias integer,
  ADD COLUMN IF NOT EXISTS aplica_vencimiento boolean;

CREATE INDEX IF NOT EXISTS idx_caf_vencimiento_cache_alert
  ON rr_gestion_soporte.caf_vencimiento_cache (nivel_alerta_caf_vencimiento, document_type, tenant_id, rut);

CREATE INDEX IF NOT EXISTS idx_caf_vencimiento_cache_rango
  ON rr_gestion_soporte.caf_vencimiento_cache (tenant_id, rut, document_type, cafserial, folio_ini, folio_fin);

CREATE INDEX IF NOT EXISTS idx_folios_rangos_cache_caf_vencimiento
  ON rr_gestion_soporte.folios_rangos_clasificados_cache (nivel_alerta_caf_vencimiento, caf_fecha_vencimiento);

ANALYZE rr_gestion_soporte.caf_vencimiento_cache;
ANALYZE rr_gestion_soporte.folios_rangos_clasificados_cache;

\echo 'caf_vencimiento_resumen'
SELECT
  document_type,
  nivel_alerta_caf_vencimiento,
  count(*) AS cafs,
  min(caf_fecha_autorizacion) AS primera_autorizacion,
  max(caf_fecha_vencimiento) AS ultimo_vencimiento
FROM rr_gestion_soporte.caf_vencimiento_resumen
GROUP BY document_type, nivel_alerta_caf_vencimiento
ORDER BY document_type, nivel_alerta_caf_vencimiento;
