-- C2C Soporte - auditoria local para mantenedores
-- Ejecutar conectado a la base local soporte.
-- No ejecutar en origen productivo.
-- No toca public ni staging_public.

CREATE TABLE IF NOT EXISTS rr_gestion_soporte.config_change_log (
  change_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  config_scope text NOT NULL,
  config_id bigint,
  action text NOT NULL,
  requested_by text NOT NULL,
  old_value jsonb,
  new_value jsonb,
  created_at timestamp without time zone NOT NULL DEFAULT now()
);

COMMENT ON TABLE rr_gestion_soporte.config_change_log IS
  'Auditoria local de cambios realizados desde mantenedores C2C Helpdesk.';

CREATE INDEX IF NOT EXISTS idx_config_change_log_scope_created
  ON rr_gestion_soporte.config_change_log (config_scope, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_config_change_log_config
  ON rr_gestion_soporte.config_change_log (config_scope, config_id, created_at DESC);

ANALYZE rr_gestion_soporte.config_change_log;

\echo 'config_change_log_ready'
SELECT count(*) AS audit_rows
FROM rr_gestion_soporte.config_change_log;
